
package FBMS.session;

import FBMS.entity.RestaurantEntity;
import Exception.ExistException;

import javax.ejb.Stateless;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.ejb.Remove;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

/**
 *
 * @author Jieqiong
 */

@Stateless
public class RestaurantSessionBean{
    
    @PersistenceContext
    private EntityManager em;
    private RestaurantEntity restaurant;
    
    public RestaurantSessionBean (){
    }
    
    /*E.4.2.1 Create restaurant*/
    @TransactionAttribute(TransactionAttributeType.REQUIRED)
    public RestaurantEntity addRestaurant(RestaurantEntity restaurant) {
        em.persist(restaurant);
        return restaurant;
    }
    
    /*E.4.2.2 Update restaurant information*/
    @TransactionAttribute(TransactionAttributeType.REQUIRED)   
    public RestaurantEntity updateRestaurant(Long restId,String restNeighbourhood,
            String restTypeOfPlace, String restCuisine,String restName) throws ExistException{
        
        restaurant=em.find(RestaurantEntity.class, restId);
        if(restaurant==null) throw new ExistException ("Restaurant doesn't exist!");
        
        //Since restId is autogenerated, it cannot be changed.
        restaurant.setRestNeighbourhood(restNeighbourhood);
        restaurant.setRestTypeOfPlace(restTypeOfPlace);
        restaurant.setRestCuisine(restCuisine);
        restaurant.setRestName(restName);
        
        em.merge(restaurant);
        return restaurant;
    }
    
}
