/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CRMS.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;

/**
 *
 * @author Jieqiong
 */
@Entity
public class CouponEntity implements Serializable {
    /*This coupon is generated by a hotel reservation reached certain amount in a single payment.
     * Member can use this coupon to purchase either attraction ticket or show ticket with a pre-defined a discount.
     * One coupon code can only be used by one member once.
     * This is not static.
     */
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long couponId;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date couponIssueDate;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date couponUsedDate;
    private String status; //New,Used, Expired
    private String department; //used at attraction or show
    @ManyToOne
    MemberEntity member; //the owner of this coupon
    @ManyToOne
    CouponTypeEntity couponType;

    public Long getCouponId() {
        return couponId;
    }

    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    public Date getCouponIssueDate() {
        return couponIssueDate;
    }

    public void setCouponIssueDate(Date couponIssueDate) {
        this.couponIssueDate = couponIssueDate;
    }

    public Date getCouponUsedDate() {
        return couponUsedDate;
    }

    public void setCouponUsedDate(Date couponUsedDate) {
        this.couponUsedDate = couponUsedDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public MemberEntity getMember() {
        return member;
    }

    public void setMember(MemberEntity member) {
        this.member = member;
    }

    public CouponTypeEntity getCouponType() {
        return couponType;
    }

    public void setCouponType(CouponTypeEntity couponType) {
        this.couponType = couponType;
    }

    

    
     

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (couponId != null ? couponId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof CouponEntity)) {
            return false;
        }
        CouponEntity other = (CouponEntity) object;
        if ((this.couponId == null && other.couponId != null) || (this.couponId != null && !this.couponId.equals(other.couponId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "CRMS.entity.CouponEntity[ id=" + couponId + " ]";
    }
    
}
